Repository kubewarden/cel-policy, pull requests merged in 2024-06, with the labels that each got.

#43 chore: add Kubewarden repository badges.
  README.md
Labels: kind/chore

#46 refactor: net CEL library
  internal/cel/library/net.go
  internal/cel/library/net_test.go
Labels: kind/enhancement

#45 refactor: crypto CEL library using builder pattern
  internal/cel/cel.go
  internal/cel/library/crypto.go
  internal/cel/library/crypto_test.go
Labels: kind/enhancement

#47 docs: update readme host cap
  README.md
  internal/cel/library/kubernetes.go
Labels: area/documentation

#48 deps: bump policy-sdk-go to v0.9.0
  .mockery.yaml
  go.mod
  go.sum
  internal/cel/library/crypto_test.go
  internal/cel/library/kubernetes_test.go
  internal/cel/library/net_test.go
  internal/cel/library/oci_test.go
  internal/cel/library/sigstore_test.go
  internal/validate/validate_test.go
  mocks/github.com/kubewarden/policy-sdk-go/pkg/capabilities/mock_WapcClient.go
Labels: kind/enhancement, dependencies

#51 refactor(sigstore): rename github in githubAction
  internal/cel/library/sigstore.go
  internal/cel/library/sigstore_test.go
Labels: kind/chore

#50 feat: return response types instead of DynMap
  internal/cel/library/crypto.go
  internal/cel/library/crypto_test.go
  internal/cel/library/sigstore.go
  internal/cel/library/sigstore_test.go
Labels: kind/enhancement

#52 feat: namespace object lazy loading
  internal/validate/namespace_object.go
  internal/validate/validate.go
  internal/validate/validate_test.go
Labels: kind/enhancement

#58 fix: responses return types
  internal/cel/library/crypto.go
  internal/cel/library/sigstore.go
Labels: kind/bug

#61 docs(kubernetes): clarify that list() returns an object list (e.g. li…
  internal/cel/library/kubernetes.go
Labels: area/documentation

#64 fix: remove timestamp from logs
  main.go
Labels: kind/bug
