Repository kubewarden/cel-policy, pull requests merged in 2024-07, with the labels that each got.

#66 feat: OCI capability to fetch image manifest and configuration.
  e2e.bats
  go.mod
  go.sum
  internal/cel/library/oci.go
  internal/cel/library/oci_test.go
Labels: kind/enhancement, kind/feature

#67 chore: bump version v1.1.0.
  artifacthub-pkg.yml
Labels: kind/chore

#68 feat: variables lazy evaluation
  internal/validate/validate.go
Labels: kind/feature

#69 refactor: simplify namespaceObject lazy-loading
  internal/validate/namespace_object.go
  internal/validate/validate.go
Labels: kind/chore

#71 chore: use more stricter golang linter configuration.
  .github/workflows/test.yml
  .golangci.yml
  Makefile
  internal/cel/cel.go
  internal/cel/library/crypto.go
  internal/cel/library/crypto_test.go
  internal/cel/library/kubernetes.go
  internal/cel/library/kubernetes_test.go
  internal/cel/library/library.go
  internal/cel/library/net_test.go
  internal/cel/library/oci_test.go
  internal/cel/library/receiver_only_val.go
  internal/cel/library/sigstore.go
  internal/cel/library/sigstore_test.go
  internal/settings/settings.go
  internal/validate/validate.go
  internal/validate/validate_test.go
  main.go
Labels: tech-debt, kind/chore
